name: PhysicalActivity
title: Physical Activity Implementation Guide
id: physical-activity
packageId: hl7.fhir.us.physical-activity
canonical: http://hl7.org/fhir/us/physical-activity
fhirVersion: 4.0.1
status: active
date: 2022-05-29
copyrightYear: 2022+
version: current
releaseLabel: Continuous Integration
jurisdiction: urn:iso:std:iso:3166#US
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 3
publisher:
  name: HL7 International - Patient Care WG
  url: http://www.hl7.org/Special/committees/patientcare
dependencies:
#  hl7.fhir.core:
#    id: r4b
#    version: 4.6.0
#    reason: |
#      This IG leverages subscription constructs pre-adopted from R4B.  Importing this IG makes the relevant terminologies available.
  hl7.fhir.us.sdoh-clinicalcare:
    id: sdoh
    version: 2.0.0
    reason: |
      While focused on social determinants of health such as appropriate housing, food availability, interpersonal violence, there is a significant overlap between the SDOH implementation guide and the exchange needs relevant to physical activity.  In both the SDOH and physical activity spaces:
    
      * The relevant measures are typically gathered by asking questions of patients or their care-giver.
      * There is not yet national consistency in how the measures are captured (or even in the need to capture the measures at all).
      * Interventions to address any identified issues will often involve non-traditional service providers (e.g. food pantries and home repair services for SDOH; personal trainers and fitness centers for physical activity).  These non-traditional service providers often do not have sophisticated EHRs or other interoperability capabilities.
      * Improving the patient situation means agreeing on and sharing information about care plans and goals between primary care providers, patients, care givers, and the non-traditional service providers.
      * There is a need to 'close the loop' on interventions to determine whether the requested intervention was performed, whether the patient is satisfied, and whether the outcome met the original objectives.
      * There may be a need to seek payment for interventions that don't fall into the traditional realm of 'healthcare services'.
    
      For all these reasons, the physical activity implementation guide builds on the standards defined by the Gravity SDOH implementation guide.  Where SDOH artifacts are overly restrictive but still relevant, this guide will define aligned but parallel profiles and will try to continue alignment in future releases.
  hl7.fhir.us.core:
    id: uscore
    version: 3.1.1
    reason: |
      US Core defines profiles that express the data elements defined in [U.S. Core Data for Interopreability (USCDI)](https://www.healthit.gov/isa/united-states-core-data-interoperability-uscdi) (which is mandated for implementation by EHR systems falling under the 21st Centure Cures Act) as well as other data elements the major U.S. EHR vendors have agreed to implement.  As such, this implementation guide is a foundation for interoperability with EHR systems in the U.S.  All profiles defined in this IG either derive from or align with US Core profiles whenever possible.
  hl7.fhir.uv.sdc:
    id: sdc
    version: 3.0.0
    reason: |
      SDC defines standards for creating, populating, extracting data from and otherwise manipulating [Questionnaires]({{site.data.fhir.path}}questionnaire.html) and [QuestionnaireResponses]({{site.data.fhir.path}}questionnaireresponse.html).  This implementation guide allows optional use of Questionnaires when gathering information from patients and care givers about physical activity levels.  It also uses questionnaires as part of the evaluation process.  Leveraging SDC ensures that questionnaires created with this guide will be able to be rendered and, where appropriate, automatically have some of their answers pre-populated into and/or extracted from using off-the-shelf tooling that already supports the SDC implementation guide.
  hl7.fhir.uv.subscriptions-backport.r4:
#  hl7.fhir.uv.subscriptions-backport:
    id: sub
    version: 1.1.0
    reason: |
      The backport IG defines standards for automatically detecting that data has changed on a system and providing notifications to interested systems.  The Gravity SDOH implementation guide uses this to allow systems to monitor for updates between EHR systems and service delivery systems.  This implementation guide allows the same approach.
  hl7.fhir.uv.extensions:
    id: ext
    version: 1.0.0
    reason: |
      Provides access to all of the 'standard' extensions defined in the core spec
  hl7.fhir.extensions.r5:
    id: r5ext
    version: 4.0.1
    reason: |
      Makes available certain R5 elements for use as part of this R4 IG
#  hl7.fhir.r4.examples:
#    id: examples
#    version: 4.0.1
description: "This implementation guide provides standardization around patient physical activity, including:&#x0a;* measures for recording a patient's level of physical activity;&#x0a;* measures to support assertions of physical activity, including device-based measures;&#x0a;* goals and care plans related to improving a patient's physical activity level;&#x0a;* orders for interventions seeking to improve a patient's physical activity level; and&#x0a;* processes to support closing the loop and evaluating the success of such interventions."
parameters:
  path-expansion-params: "../../input/terminology-settings.xml"
  path-liquid: "liquid"
  apply-contact: false
  apply-publisher: false
  default-contact: true
  default-publisher: true
  globals-in-artifacts: true
instanceOptions:
  setMetaProfile: never
pages:
  index.xml:
    title: Welcome to the Physical Activity IG
    background.xml: 
      title: Importance of Physical Activity
    scenarios.xml: 
      title: Implementation Scenarios
    fhir.xml: 
      title: FHIR Background
    design.xml: 
      title: Design Considerations
    conformance.xml: 
      title: Conformance Expectations
    measures.xml: 
      title: Physical Activity Measures
    interventions.xml: 
      title: Plans & Interventions
    workflow.xml: 
     title: Physical Activity Workflow
    security.xml: 
      title: Privacy and Security Considerations
    artifacts.xml: 
      title: IG Artifacts
    downloads.xml: 
      title: Downloads
    credits.xml: 
      title: Credits
    openissues.xml: 
      title: Open Issues
resources:
  ExampleRelatedPerson:
    exampleCanonical: PARelatedPerson
  ExampleEVSDaysPerWeek:
    exampleCanonical: PAObservationEVSDaysPerWeek
  ExampleEVSMinutesPerDay:
    exampleCanonical: PAObservationEVSMinutesPerDay
  ExampleEVSMinutesPerWeek:
    exampleCanonical: PAObservationEVSMinutesPerWeek
  ExampleStrengthDaysPerWeek:
    exampleCanonical: PAObservationStrengthDaysPerWeek
  ExampleCondition:
    exampleCanonical: PAConditionLowPA
  ExampleCarePlan:
    exampleCanonical: PACarePlan
  ExampleGoal:
    exampleCanonical: PAGoal
  ExampleServiceRequest:
    exampleCanonical: PAServiceRequest
  ExampleFulfillmentTask:
    exampleCanonical: PATaskForReferralManagement
  ExampleReport:
    exampleCanonical: PADiagnosticReport
  ExampleActivityGroup:
    exampleCanonical: PAObservationActivityGroup
  ExampleActivityType:
    exampleCanonical: PAObservationActivityMeasure
  ExampleActivityDuration:
    exampleCanonical: PAObservationActivityMeasure
  ExampleActivityModerate:
    exampleCanonical: PAObservationActivityMeasure
  ExampleActivityVigorous:
    exampleCanonical: PAObservationActivityMeasure
  ExampleActivityPeakHR:
    exampleCanonical: PAObservationActivityMeasure
  ExampleActivityCalories:
    exampleCanonical: PAObservationActivityMeasure
  ExampleDailySteps:
    exampleCanonical: PAObservationTimeMeasure
  ExamplePeakDailyHeartRate:
    exampleCanonical: PAObservationTimeMeasure
  ExampleAverageRestingHeartRate:
    exampleCanonical: PAObservationTimeMeasure
  ExampleCaloriesPerDay:
    exampleCanonical: PAObservationTimeMeasure
  ExampleSubscriptionWebhook:
    exampleCanonical: BackportSubscription
  ExampleSubscriptionEmail:
    exampleCanonical: BackportSubscription
  ExampleSubscriptionSMS:
    exampleCanonical: BackportSubscription
  ExampleSubscriptionBundleWithIds:
    exampleCanonical: BackportSubscriptionNotificationR4
  ExampleSubscriptionBundleWithNoIds:
    exampleCanonical: BackportSubscriptionNotificationR4
  ExampleSubscriptionStatusWithIds:
    exampleCanonical: BackportSubscriptionStatusR4
  ExampleSubscriptionStatusWithNoIds:
    exampleCanonical: BackportSubscriptionStatusR4
#  Scen1ExercisePrescriptionScenario:
#    groupingId: ex-scenario-1
#  Scen1CarePlanV1:
#    groupingId: ex-scenario-1
#  Scen1CarePlanV2:
#    groupingId: ex-scenario-1
#  Scen1CarePlanBundleV1:
#    groupingId: ex-scenario-1
#  Scen1CarePlanBundleV2:
#    groupingId: ex-scenario-1
#  Scen1GoalV1:
#    groupingId: ex-scenario-1
#  Scen1GoalV2:
#    groupingId: ex-scenario-1
#  Scen1GoalBundleV1:
#    groupingId: ex-scenario-1
#  Scen1GoalBundleV2:
#    groupingId: ex-scenario-1
#  Scen1ExerciseRx:
#    groupingId: ex-scenario-1
#  Scen1ExerciseRxBundle:
#    groupingId: ex-scenario-1
#  Scen1ObservationDaysPerWeek:
#    groupingId: ex-scenario-1
#  Scen1ObservationMinsPerDay:
#    groupingId: ex-scenario-1
#  Scen1ObservationMinsPerWeek:
#    groupingId: ex-scenario-1
#  Scen1ObservationStrengthDaysPerWeek:
#    groupingId: ex-scenario-1
#  Scen1OrgGoodhealth:
#    groupingId: ex-scenario-1
#  Scen1PatientKhatun:
#    groupingId: ex-scenario-1
#  Scen1PractitionerPatel:
#    groupingId: ex-scenario-1
#  Scen1RolePatel:
#    groupingId: ex-scenario-1
#  Scen2ProviderToPersonaltrainerReferral:
#    groupingId: ex-scenario-2
#  Scen2SubscriptionEhr:
#    groupingId: ex-scenario-2
#  Scen2SubscriptionGetfit:
#    groupingId: ex-scenario-2
#  Scen2PractitionerTrainerSearchsetBundle:
#    groupingId: ex-scenario-2
#  Scen2RoleWang:
#    groupingId: ex-scenario-2
#  Scen2PractitionerWang:
#    groupingId: ex-scenario-2
#  Scen2RoleMatthew:
#    groupingId: ex-scenario-2
#  Scen2PractitionerMatthew:
#    groupingId: ex-scenario-2
#  Scen2SubscriptionNotificationNewtaskBundle:
#    groupingId: ex-scenario-2
#  Scen2parameters:
#    groupingId: ex-scenario-2
#  Scen2TaskGetfitResponseBundle:
#    groupingId: ex-scenario-2
#  Scen2TaskGetfit:
#    groupingId: ex-scenario-2
#  Scen2TaskGetfitV2:
#    groupingId: ex-scenario-2
#  Scen2PatientJohansson:
#    groupingId: ex-scenario-2
#  Scen2Servicerequest:
#    groupingId: ex-scenario-2
#  Scen2TaskFit4life:
#    groupingId: ex-scenario-2
#  Scen2TaskFit4lifeV2:
#    groupingId: ex-scenario-2
#  Scen2TaskFit4lifeV3:
#    groupingId: ex-scenario-2
#  Scen2TaskFit4lifeResponseBundle:
#    groupingId: ex-scenario-2
#  Scen2ConditionResponseBundle:
#    groupingId: ex-scenario-2
#  Scen2ConditionCardio:
#    groupingId: ex-scenario-2
#  Scen2ObservationResponseBundle:
#    groupingId: ex-scenario-2
#  Scen2ObsDaysPerWeek:
#    groupingId: ex-scenario-2
#  Scen2ObsMinutesPerDay:
#    groupingId: ex-scenario-2
#  Scen2NotificationUpdatedtaskBundle:
#    groupingId: ex-scenario-2
#  Scen2parameters2:
#    groupingId: ex-scenario-2
#  Scen2NotificationCompletedtaskBundle:
#    groupingId: ex-scenario-2
#  Scen2parameters3:
#    groupingId: ex-scenario-2
#  Scen2DiagnosticReportObservationsResponseBundle:
#    groupingId: ex-scenario-2
#  Scen2DiagnosticReport:
#    groupingId: ex-scenario-2
#  Scen2ObsDaysPerWeek2:
#    groupingId: ex-scenario-2
#  Scen2ObsMinutesPerDay2:
#    groupingId: ex-scenario-2
#  Scen2ObsActivityCalories:
#    groupingId: ex-scenario-2
#  Scen2ObsActivityPeakHR:
#    groupingId: ex-scenario-2
#  Scen2OrgFit4life:
#    groupingId: ex-scenario-2
#  Scen2OrgGetfittraining:
#    groupingId: ex-scenario-2
#  Scen3ProviderToYMCAReferral:
#    groupingId: ex-scenario-3
#  Scen3SubscriptionEhr:
#    groupingId: ex-scenario-3
#  Scen3TaskYMCA:
#    groupingId: ex-scenario-3
#  Scen3TaskYMCAV2:
#    groupingId: ex-scenario-3
#  Scen3TaskYMCAV3:
#    groupingId: ex-scenario-3
#  Scen3PatientShevchenko:
#    groupingId: ex-scenario-3
#  Scen3Servicerequest:
#    groupingId: ex-scenario-3
#  Scen3NotificationUpdatedtaskBundle:
#    groupingId: ex-scenario-3
#  Scen3parameters1:
#    groupingId: ex-scenario-3
#  Scen3NotificationCompletedtaskBundle:
#    groupingId: ex-scenario-3
#  Scen3parameters2:
#    groupingId: ex-scenario-3
#  Scen3OrgMainclinic:
#    groupingId: ex-scenario-3
#  Scen3OrgYMCA:
#    groupingId: ex-scenario-3
#  Scen3PractitionerBlackrock:
#    groupingId: ex-scenario-3
#  Scen3RoleBlackrock:
#    groupingId: ex-scenario-3
#  Scen4PhysicalActivityPlan:
#    groupingId: ex-scenario-4
#  Scen4CarePlan:
#    groupingId: ex-scenario-4
#  Scen4Goal1:
#    groupingId: ex-scenario-4
#  Scen4Goal1V2:
#    groupingId: ex-scenario-4
#  Scen4Goal2:
#    groupingId: ex-scenario-4
#  Scen4Goal2V2:
#    groupingId: ex-scenario-4
#  Scen4ObservationActivityType:
#    groupingId: ex-scenario-4
#  Scen4ObservationEVSMinutesPerDay:
#    groupingId: ex-scenario-4
#  Scen4ObservationPeakDailyHeartRate:
#    groupingId: ex-scenario-4
#  Scen4ObservationEVSMinutesPerDay2:
#    groupingId: ex-scenario-4
#  Scen4ObservationCaloriesPerDay:
#    groupingId: ex-scenario-4
#  Scen4ObservationDailySteps:
#    groupingId: ex-scenario-4
#  Scen4ObservationEVSMinutesPerDay3:
#    groupingId: ex-scenario-4
#  Scen4TaskFillSurvey:
#    groupingId: ex-scenario-4
#  Scen4TaskFillSurveyV2:
#    groupingId: ex-scenario-4
#  Scen4TaskFillSurvey2:
#    groupingId: ex-scenario-4
#  Scen4TaskFillSurvey2V2:
#    groupingId: ex-scenario-4
#  Scen4TaskReviewVideo:
#    groupingId: ex-scenario-4
#  Scen4TaskReviewVideoV2:
#    groupingId: ex-scenario-4
#  Scen4Questionnaire:
#    groupingId: ex-scenario-4
#  Scen4QuestionnaireResponse:
#    groupingId: ex-scenario-4
#  Scen4QuestionnaireResponse2:
#    groupingId: ex-scenario-4
#  Scen4PatientScarborough:
#    groupingId: ex-scenario-4
#  Scen4Practitioner:
#    groupingId: ex-scenario-4
#  Scen5ActivityAndGlucoseObservations:
#    groupingId: ex-scenario-5
#  Scen5ObservationActivityType:
#    groupingId: ex-scenario-5
#  Scen5ObservationEVSMinutesPerDay:
#    groupingId: ex-scenario-5
#  Scen5ObservationPeakDailyHeartRate:
#    groupingId: ex-scenario-5
#  Scen5ObservationCaloriesPerDay:
#    groupingId: ex-scenario-5
#  Scen5ObservationDailySteps:
#    groupingId: ex-scenario-5
#  Scen5ObservationBloodGlucose1:
#    groupingId: ex-scenario-5
#  Scen5ObservationBloodGlucose2:
#    groupingId: ex-scenario-5
#  Scen5ObservationsResponseBundle:
#    groupingId: ex-scenario-5
#  Scen5RelatedpersonNadia:
#    groupingId: ex-scenario-5
#  Scen5PatientRosalie:
#    groupingId: ex-scenario-5
menu:
  Contents: toc.html
  Home: index.html
  Background:
    Why Physical Activity?: background.html
    Implementation Scenarios: scenarios.html
    FHIR Background: fhir.html
    Design Considerations: design.html
    Credits: credits.html
  Specification:
    Conformance Expectations: conformance.html
    Measures: measures.html
    Plans & Interventions: interventions.html
    Workflow: workflow.html
    Privacy & Security: security.html
  Artifacts: artifacts.html
  Support:
    Project Home: https://confluence.hl7.org/display/PC/Physical+Activity
    Help & Discussions: https://chat.fhir.org/#narrow/stream/327137-Physical-Activity
    Downloads: downloads.html